"""empty message

Revision ID: 1d92f396e877
Revises: e85fc14ec496
Create Date: 2019-11-11 20:58:46.751250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d92f396e877'
down_revision = 'e85fc14ec496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('Show', sa.Column('show_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'show_time')
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
