"""empty message

Revision ID: 1fd78bf6a4e5
Revises: 1d92f396e877
Create Date: 2019-11-11 21:12:23.374958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fd78bf6a4e5'
down_revision = '1d92f396e877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.String(), nullable=True))
    op.drop_column('Show', 'show_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###
