"""empty message

Revision ID: f970c746141e
Revises: 1fd78bf6a4e5
Create Date: 2019-11-11 21:24:45.185387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f970c746141e'
down_revision = '1fd78bf6a4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('show_time', sa.DateTime(), nullable=True))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Show', 'show_time')
    # ### end Alembic commands ###
